version: "3.2"
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
     - 15672:15672
    networks:
      - tp3_net

  rabbitmq_config:
    container_name: rabbitmq_config
    image: rabbitmq-config:latest
    networks:
      - tp3_net

  client:
    container_name: client
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: client
    environment:
      - POSTS_FILE=/var/data/the-reddit-irl-dataset-posts.csv
      - COMMENTS_FILE=/var/data/the-reddit-irl-dataset-comments.csv
      - CHUNK_SIZE=1000
      - SERVER_ADDRESS=server:9090
    volumes:
      - ${PWD}/data/the-reddit-irl-dataset-posts.csv:/var/data/the-reddit-irl-dataset-posts.csv
      - ${PWD}/data/the-reddit-irl-dataset-comments.csv:/var/data/the-reddit-irl-dataset-comments.csv
    networks:
      - tp3_net

  server:
    container_name: server
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: server
    environment:
      - RABBITMQ_HOST=rabbitmq
      - SERVER_ADDRESS=0.0.0.0:9090
      - CHUNK_SIZE=1000
      - POSTS_PRODUCER_ADDRESS=post_producer:9090
      - COMMENTS_PRODUCER_ADDRESS=comment_producer:9090
    networks:
      - tp3_net

  post_producer:
    container_name: post_producer
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: post_producer
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  comment_producer:
    container_name: comment_producer
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: comment_producer
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  best_meme_filter:
    container_name: best_meme_filter
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: best_meme_filter
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  comment_college_filter:
    container_name: comment_college_filter
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: comment_college_filter
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  comment_sentiment_extractor:
    container_name: comment_sentiment_extractor
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: comment_sentiment_extractor
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  mean_calculator:
    container_name: mean_calculator
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: mean_calculator
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  post_average_filter:
    container_name: post_average_filter
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: post_average_filter
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  post_college_filter:
    container_name: post_college_filter
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: post_college_filter
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  post_sentiment_calculator:
    container_name: post_sentiment_calculator
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: post_sentiment_calculator
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  post_sentiment_filter:
    container_name: post_sentiment_filter
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: post_sentiment_filter
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  score_extractor:
    container_name: score_extractor
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: score_extractor
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  url_extractor:
    container_name: url_extractor
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: url_extractor
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  task_management_0:
    container_name: task_management_0
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: task_management
    environment:
      - SERVICE_LIST_FILE=services.txt
      - SERVICE_PORT=6789
      - TIMEOUT_SEC=80
      - SEC_BETWEEN_REQUESTS=5
      - PROCESS_ID=0
    volumes:
      - ./services.txt:/tp2/services.txt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tp3_net

  task_management_1:
    container_name: task_management_1
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: task_management
    environment:
      - SERVICE_LIST_FILE=services.txt
      - SERVICE_PORT=6789
      - TIMEOUT_SEC=80
      - SEC_BETWEEN_REQUESTS=5
      - PROCESS_ID=1
    volumes:
      - ./services.txt:/tp2/services.txt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tp3_net
  
  task_management_2:
    container_name: task_management_2
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: task_management
    environment:
      - SERVICE_LIST_FILE=services.txt
      - SERVICE_PORT=6789
      - TIMEOUT_SEC=80
      - SEC_BETWEEN_REQUESTS=5
      - PROCESS_ID=2
    volumes:
      - ./services.txt:/tp2/services.txt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tp3_net
  
  task_management_3:
    container_name: task_management_3
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: task_management
    environment:
      - SERVICE_LIST_FILE=services.txt
      - SERVICE_PORT=6789
      - TIMEOUT_SEC=80
      - SEC_BETWEEN_REQUESTS=5
      - PROCESS_ID=3
    volumes:
      - ./services.txt:/tp2/services.txt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tp3_net
    
networks:
  tp3_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
