version: "3.2"
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
     - 15672:15672
    networks:
      - tp3_net

  rabbitmq_config:
    container_name: rabbitmq_config
    image: rabbitmq-config:latest
    networks:
      - tp3_net

  results_consumer:
    container_name: results_consumer
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: results_consumer
    environment:
      - RABBITMQ_HOST=rabbitmq
      - OUTPUT_PATH=/var/data/output.txt
    volumes:
      - ${PWD}/data/output.txt:/var/data/output.txt
    networks:
      - tp3_net

  post_producer:
    container_name: post_producer
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: post_producer
    environment:
      - RABBITMQ_HOST=rabbitmq
      - POSTS_FILE=/var/data/the-reddit-irl-dataset-posts.csv
    volumes:
      - ${PWD}/data/the-reddit-irl-dataset-posts.csv:/var/data/the-reddit-irl-dataset-posts.csv
    networks:
      - tp3_net

  comment_producer:
    container_name: comment_producer
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: comment_producer
    environment:
      - RABBITMQ_HOST=rabbitmq
      - COMMENTS_FILE=/var/data/the-reddit-irl-dataset-comments.csv
      - CONSUMERS=2
    volumes:
      - ${PWD}/data/the-reddit-irl-dataset-comments.csv:/var/data/the-reddit-irl-dataset-comments.csv
    networks:
      - tp3_net

  best_meme_filter:
    container_name: best_meme_filter
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: best_meme_filter
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  comment_college_filter:
    container_name: comment_college_filter
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: comment_college_filter
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  comment_sentiment_extractor:
    container_name: comment_sentiment_extractor
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: comment_sentiment_extractor
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  mean_calculator:
    container_name: mean_calculator
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: mean_calculator
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  post_average_filter:
    container_name: post_avergate_filter
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: post_average_filter
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  post_college_filter:
    container_name: post_college_filter
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: post_college_filter
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  post_sentiment_calculator:
    container_name: post_sentiment_calculator
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: post_sentiment_calculator
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  post_sentiment_filter:
    container_name: post_sentiment_filter
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: post_sentiment_filter
    environment:
      - PRODUCERS=2
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  score_extractor:
    container_name: score_extractor
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: score_extractor
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - tp3_net

  url_extractor:
    container_name: url_extractor
    image: memes-nodes:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: url_extractor
    environment:
      - RABBITMQ_HOST=rabbitmq
      - CONSUMERS=2
    networks:
      - tp3_net

  task_management1:
    container_name: task_management1
    image: task_management:latest
    depends_on:
      rabbitmq_config:
        condition: service_completed_successfully
    command: task_management
    environment:
      - SERVICE_LIST_FILE=services.txt
      - SERVICE_PORT=6789
      - TIMEOUT_SEC=80
      - SEC_BETWEEN_REQUESTS=5
    volumes:
      - ./services.txt:/services.txt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tp3_net
    
networks:
  tp3_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
